baseURL = "http://robelcodes.github.io/documentation-dev/"
languageCode = "en-us"
title = "My Hugo Relearn Site Dev"
theme = "relearn"


# Add or update the following line in both files:
publishDir = "docs"
