baseURL = "https://robel-codes.github.io/my-hugo-site/"
languageCode = "en-us"
title = "My Hugo Relearn Site Prod"
theme = "relearn"


# Add or update the following line in both files:
publishDir = "docs"
