baseURL = "https://robel-codes.github.io/my-hugo-site/dev/"
languageCode = "en-us"
title = "My Hugo Relearn Site Dev"
theme = "relearn"


# Add or update the following line in both files:
publishDir = "docs"
